FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

COPY . .

ARG VITE_TENANT_LOGIN_URL
ARG VITE_OCTOPUS_TRACK_LOGIN_URL
ARG VITE_OCTOPUS_FLOW_LOGIN_URL
ENV VITE_TENANT_LOGIN_URL=${VITE_TENANT_LOGIN_URL:-https://octopus.qeva.xyz/tenant.html#/login}
ENV VITE_OCTOPUS_TRACK_LOGIN_URL=${VITE_OCTOPUS_TRACK_LOGIN_URL:-https://octopus.qeva.xyz}
ENV VITE_OCTOPUS_FLOW_LOGIN_URL=${VITE_OCTOPUS_FLOW_LOGIN_URL:-https://login-flow.octopustrack.shop}

RUN npm run build:landing

FROM nginx:1.27-alpine

COPY nginx/landing.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist-landing /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
