[mypy]
python_version = 3.12
ignore_missing_imports = True
no_strict_optional = True
allow_untyped_defs = True
warn_unused_ignores = False
exclude = alembic/|app/tests/

[mypy-app.services.afip_sdk_service]
ignore_errors = True

[mypy-app.services.ai_chat_service]
ignore_errors = True

[mypy-app.services.ai_quote_service]
ignore_errors = True

[mypy-app.routers.admin]
ignore_errors = True

[mypy-app.routers.pdf_test]
ignore_errors = True

[mypy-app.services.voucher_service]
ignore_errors = True

[mypy-app.services.purchase_order_service]
ignore_errors = True

[mypy-app.services.category_service]
ignore_errors = True

[mypy-app.services.excel_service]
ignore_errors = True

[mypy-app.services.cash_register_service]
ignore_errors = True

[mypy-app.schemas.voucher]
ignore_errors = True

[mypy-app.routers.products]
ignore_errors = True