"""add_ai_provider_configs_table

Revision ID: 07c058b85650
Revises: b9c1d2e3f4a5
Create Date: 2026-03-12 17:43:38.953895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07c058b85650'
down_revision: Union[str, Sequence[str], None] = 'b9c1d2e3f4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_provider_configs',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('api_key_last4', sa.String(length=4), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('default_model', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'provider', name='uq_ai_provider_business')
    )
    op.create_index(op.f('ix_ai_provider_configs_business_id'), 'ai_provider_configs', ['business_id'], unique=False)
    op.create_index(op.f('ix_ai_provider_configs_id'), 'ai_provider_configs', ['id'], unique=False)
    op.alter_column('products', 'customer_terms',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Términos populares / jerga del cliente separados por comas. Usados por el agente IA para matching semántico.',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'customer_terms',
               existing_type=sa.TEXT(),
               comment='Términos populares / jerga del cliente separados por comas. Usados por el agente IA para matching semántico.',
               existing_nullable=True)
    op.drop_index(op.f('ix_ai_provider_configs_id'), table_name='ai_provider_configs')
    op.drop_index(op.f('ix_ai_provider_configs_business_id'), table_name='ai_provider_configs')
    op.drop_table('ai_provider_configs')
    # ### end Alembic commands ###
