"""add_product_extra_cost

Revision ID: 20509a0afd1e
Revises: 8feee9046942
Create Date: 2026-02-06 16:34:31.990477

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '20509a0afd1e'
down_revision: str | Sequence[str] | None = '8feee9046942'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('extra_cost', sa.Numeric(precision=5, scale=2), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'extra_cost')
    # ### end Alembic commands ###
