"""add_general_discount_to_vouchers

Revision ID: 594c26beebec
Revises: ddbc7045782f
Create Date: 2026-02-25 06:20:25.373309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '594c26beebec'
down_revision: Union[str, Sequence[str], None] = 'ddbc7045782f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vouchers', sa.Column('general_discount', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vouchers', 'general_discount')
    # ### end Alembic commands ###
