"""add_chat_conversations_and_messages

Revision ID: 70253179bd70
Revises: 9f4c2b7d1a8e
Create Date: 2026-03-15 22:30:26.449970

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '70253179bd70'
down_revision: str | Sequence[str] | None = '9f4c2b7d1a8e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
