"""add_purchase_orders_tables

Revision ID: 72186945074f
Revises: fa3bbaaf3d7b
Create Date: 2026-02-24 14:04:05.649192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72186945074f'
down_revision: Union[str, Sequence[str], None] = 'fa3bbaaf3d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', name='purchaseorderstatus'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_iva', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_business_id'), 'purchase_orders', ['business_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_category_id'), 'purchase_orders', ['category_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_id'), 'purchase_orders', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_status'), 'purchase_orders', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('system_stock', sa.Integer(), nullable=False),
    sa.Column('counted_stock', sa.Integer(), nullable=True),
    sa.Column('quantity_to_order', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('iva_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('iva_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_items_id'), 'purchase_order_items', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_order_items_product_id'), 'purchase_order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_items_purchase_order_id'), 'purchase_order_items', ['purchase_order_id'], unique=False)
    op.drop_constraint(op.f('uq_business_payment_code'), 'payment_methods', type_='unique')
    op.create_index(op.f('ix_payment_methods_id'), 'payment_methods', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_category_discounts_id'), 'supplier_category_discounts', ['id'], unique=False)
    op.create_index(op.f('ix_voucher_payments_id'), 'voucher_payments', ['id'], unique=False)
    op.create_index(op.f('ix_vouchers_related_voucher_id'), 'vouchers', ['related_voucher_id'], unique=False)
    op.drop_constraint(op.f('fk_vouchers_related_voucher_id'), 'vouchers', type_='foreignkey')
    op.drop_constraint(op.f('fk_vouchers_invoiced_voucher_id'), 'vouchers', type_='foreignkey')
    op.create_foreign_key(None, 'vouchers', 'vouchers', ['related_voucher_id'], ['id'])
    op.create_foreign_key(None, 'vouchers', 'vouchers', ['invoiced_voucher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vouchers', type_='foreignkey')
    op.drop_constraint(None, 'vouchers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_vouchers_invoiced_voucher_id'), 'vouchers', 'vouchers', ['invoiced_voucher_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_vouchers_related_voucher_id'), 'vouchers', 'vouchers', ['related_voucher_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_vouchers_related_voucher_id'), table_name='vouchers')
    op.drop_index(op.f('ix_voucher_payments_id'), table_name='voucher_payments')
    op.drop_index(op.f('ix_supplier_category_discounts_id'), table_name='supplier_category_discounts')
    op.drop_index(op.f('ix_payment_methods_id'), table_name='payment_methods')
    op.create_unique_constraint(op.f('uq_business_payment_code'), 'payment_methods', ['business_id', 'code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_purchase_order_items_purchase_order_id'), table_name='purchase_order_items')
    op.drop_index(op.f('ix_purchase_order_items_product_id'), table_name='purchase_order_items')
    op.drop_index(op.f('ix_purchase_order_items_id'), table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_status'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_category_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_business_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    # ### end Alembic commands ###
