"""add_purchase_order_numbering

Revision ID: ddbc7045782f
Revises: 72186945074f
Create Date: 2026-02-24 22:43:55.065379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddbc7045782f'
down_revision: Union[str, Sequence[str], None] = '72186945074f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('businesses', sa.Column('last_purchase_order_number', sa.String(length=8), nullable=True, server_default='00000000'))
    op.add_column('purchase_orders', sa.Column('sale_point', sa.String(length=4), nullable=False, server_default='0001'))
    op.add_column('purchase_orders', sa.Column('number', sa.String(length=8), nullable=False, server_default='00000001'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'number')
    op.drop_column('purchase_orders', 'sale_point')
    op.drop_column('businesses', 'last_purchase_order_number')
    # ### end Alembic commands ###
