"""add supplier category discounts table

Revision ID: fcd7abe2eb17
Revises: c7a3e1f90d22
Create Date: 2026-02-12 18:29:32.347435

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fcd7abe2eb17'
down_revision: str | Sequence[str] | None = 'c7a3e1f90d22'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_categories_category_id'), table_name='supplier_categories')
    op.drop_index(op.f('ix_supplier_categories_supplier_id'), table_name='supplier_categories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_supplier_categories_supplier_id'), 'supplier_categories', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_categories_category_id'), 'supplier_categories', ['category_id'], unique=False)
    # ### end Alembic commands ###
